### ISSUE TITLE
Fatal error: Uncaught TypeError: file_exists() expects parameter 1 to be a valid path, null given

### ISSUE THREAD

**Issue by ghost** [php-taskman/github#9]
When calling `github.release.create` task without the body option it gives me the following error:
```
Fatal error: Uncaught TypeError: file_exists() expects parameter 1 to be a valid path, null given in /home/verbral/github/verbruggenalex/drupal-project/vendor/phptaskman/github/src/Plugin/Task/ReleaseCreateTask.php:45
```

I'm not sure whether we should add a condition on `$arguments['body'] !== null` or changing the default value to be an empty string:

https://github.com/php-taskman/github/blob/e1029aec7cb52a31d356122f9142c48e271e18ff/src/Plugin/Task/ReleaseCreateTask.php#L45
https://github.com/php-taskman/github/blob/e1029aec7cb52a31d356122f9142c48e271e18ff/src/Plugin/Task/ReleaseCreateTask.php#L34

Issue probably exists on both release create and release edit...

**Comment by drupol** [comment]
aaah... the condition needs to be updated I think.

**Comment by ghost** [comment]
I'll make a PR tomorrow. Wanted to create a branch on this repo but I seemingly don't have the rights:

```
git push --set-upstream origin issue/9
ERROR: Permission to php-taskman/github.git denied to verbruggenalex.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by drupol** [comment]
> I'll make a PR tomorrow. Wanted to create a branch on this repo but I seemingly don't have the rights:
> 
> ```
> git push --set-upstream origin issue/9
> ERROR: Permission to php-taskman/github.git denied to verbruggenalex.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Fixed!
